/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_generatekeyresult_free: (a: number, b: number) => void;
export const generatekeyresult_key_share: (a: number) => [number, number];
export const generatekeyresult_pub_key: (a: number) => [number, number];
export const generate_key: (a: number, b: number, c: any, d: number, e: number, f: number) => any;
export const sign: (a: number, b: number, c: any, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number) => any;
export const batch_size: () => number;
export const random_generator: (a: number, b: number) => [number, number, number];
export const random_generator_free: (a: number) => void;
export const threshold_signer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const threshold_signer_free: (a: number) => void;
export const setup: (a: number, b: number, c: any) => any;
export const precompute: (a: any, b: number, c: number, d: any) => any;
export const local_sign: (a: number, b: number, c: number, d: any) => [number, number, number];
export const get_r_from_precompute: (a: any) => [number, number, number];
export const local_verify: (a: number, b: number, c: number, d: any, e: number, f: number, g: number, h: number) => [number, number, number];
export const sign_deprecated: (a: any, b: number, c: number, d: number, e: number, f: number, g: any) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure108_externref_shim: (a: number, b: number, c: any) => void;
export const closure128_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
