/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function process_ga1(a: number, b: number, c: number): void;
export function random_generator(a: number, b: number, c: number): void;
export function random_generator_free(a: number): void;
export function threshold_signer_hack(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number): void;
export function threshold_signer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function threshold_signer_free(a: number): void;
export function setup(a: number, b: number): number;
export function parties_hack(a: number, b: number): void;
export function precompute_hack(a: number, b: number, c: number): number;
export function precompute(a: number, b: number, c: number): number;
export function local_sign_hack(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function local_sign(a: number, b: number, c: number, d: number, e: number): void;
export function get_r_from_precompute(a: number, b: number): void;
export function local_verify_hack(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function local_verify(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function sign(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function batch_size(): number;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h818c05d57f677580(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function wasm_bindgen__convert__closures__invoke3_mut__h09737911ec6fe149(a: number, b: number, c: number, d: number, e: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h4f1c3ec675e015fc(a: number, b: number, c: number, d: number): void;
