/**
 * Types for the JavaScript-WebAssembly message broker interface.
 *
 * NOTE: These are not autogenerated by wasm-bindgen.
 */
export type SessionId = string;
export type PartyIdx = number;
export type MsgType = string;
export type MsgData = Uint8Array;
export interface MessageBroker {
  /**
   * The session identifer.
   */
  session_id: SessionId;
  /**
   * The message sender associated with this message broker instance.
   */
  sender_id: PartyIdx;
  /**
   * Send message data `mdata` of type `mtype` to party `to`.
   * @param to
   * @param mtype
   * @param mdata
   */
  send(to: PartyIdx, mtype: MsgType, mdata: MsgData): Promise<void>;
  /**
   * Read the next message of type `mtype` from party `from`.
   * @param from
   * @param mtype
   */
  receive(from: PartyIdx, mtype: MsgType): Promise<MsgData>;
}
